name: Create Archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '@(ModuleName).zip'
        exclusions: '*.git* /*node_modules/* .editorconfig changelog.md update.json LICENSE setup.py README.md'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "@(ModuleName).zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: changelog.md
